# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
pt:
  languageCode: "pt"
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 10
      - name: Postagens
        url: '#posts'
        weight: 20
      - name: Projetos
        url: '#projects'
        weight: 30
      - name: Palestras
        url: '#talks'
        weight: 40
      - name: Publicações
        url: '#featured'
        weight: 50
      - name: Downloads
        url: '/downloads'
        weight: 55
      - name: Contato
        url: '#contact'
        weight: 60

#en:
#  languageCode: en-us
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
